// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHealthMonitoring.Context;

#nullable disable

namespace SmartHealthMonitoring.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260514004106_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartHealthMonitoring.Models.AiInsight", b =>
                {
                    b.Property<Guid>("InsightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AiAdvice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PredictedDisease")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("RiskPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("InsightId")
                        .HasName("PK__AiInsigh__6A3F54F42AC19670");

                    b.HasIndex("PatientId");

                    b.ToTable("AiInsights");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.Alert", b =>
                {
                    b.Property<Guid>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("MetricId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AlertId")
                        .HasName("PK__Alerts__EBB16A8D9D3D0B06");

                    b.HasIndex("MetricId");

                    b.HasIndex(new[] { "PatientId" }, "IX_Alerts_PatientId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("SymptomsNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AppointmentId")
                        .HasName("PK_Appointments");

                    b.HasIndex("PatientId");

                    b.HasIndex("SlotId")
                        .IsUnique();

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Appointments_Status");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.AppointmentSlot", b =>
                {
                    b.Property<Guid>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsBooked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("SlotId");

                    b.HasIndex("DoctorId");

                    b.ToTable("AppointmentSlots");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.AuditLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LogId")
                        .HasName("PK__AuditLog__5E548648307A41C9");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.Doctor", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DoctorId")
                        .HasName("PK__Doctors__2DC00EBF5811057E");

                    b.HasIndex(new[] { "UserId" }, "UQ__Doctors__1788CC4DD1F1C5F0")
                        .IsUnique();

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.GlobalThreshold", b =>
                {
                    b.Property<int>("ThresholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThresholdId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxAge")
                        .HasColumnType("int");

                    b.Property<int>("MetricTypeId")
                        .HasColumnType("int");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.Property<decimal>("SafeMaxValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SafeMinValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SeverityLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WarningMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ThresholdId")
                        .HasName("PK__GlobalTh__8E87A7D03DD2C22C");

                    b.HasIndex(new[] { "MetricTypeId", "MinAge", "MaxAge" }, "UQ_GlobalThresholds")
                        .IsUnique();

                    b.ToTable("GlobalThresholds");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.HealthMetric", b =>
                {
                    b.Property<Guid>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("MeasuredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MetricTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Manual");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MetricId")
                        .HasName("PK__HealthMe__561056A5226DE9F4");

                    b.HasIndex("MetricTypeId");

                    b.HasIndex(new[] { "MeasuredAt" }, "IX_HealthMetrics_MeasuredAt");

                    b.HasIndex(new[] { "PatientId" }, "IX_HealthMetrics_PatientId");

                    b.ToTable("HealthMetrics");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.LabResult", b =>
                {
                    b.Property<Guid>("LabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DoctorNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResultFileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("LabId")
                        .HasName("PK__LabResul__EDBD68DADF86C556");

                    b.HasIndex("RecordId");

                    b.ToTable("LabResults");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.MedicalRecord", b =>
                {
                    b.Property<Guid>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PrescriptionNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Open");

                    b.Property<string>("Symptoms")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecordId")
                        .HasName("PK_MedicalRecords");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasFilter("[AppointmentId] IS NOT NULL");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_MedicalRecords_PatientId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.MetricType", b =>
                {
                    b.Property<int>("MetricTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetricTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MetricTypeId")
                        .HasName("PK__MetricTy__79DBA064F17BDC53");

                    b.HasIndex(new[] { "Code" }, "UQ__MetricTy__A25C5AA7F74B0D70")
                        .IsUnique();

                    b.ToTable("MetricTypes");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E12F881E2DE");

                    b.HasIndex(new[] { "UserId" }, "IX_Notifications_UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BloodType")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PatientId")
                        .HasName("PK__Patients__970EC366172A5CE9");

                    b.HasIndex(new[] { "UserId" }, "UQ__Patients__1788CC4D2452BB1A")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1ACEE3C051");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B6160C50DD254")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C118BF1FE");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E432499C32")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534EAABED36")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.AiInsight", b =>
                {
                    b.HasOne("SmartHealthMonitoring.Models.Patient", "Patient")
                        .WithMany("AiInsights")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_AiInsights_Patients");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.Alert", b =>
                {
                    b.HasOne("SmartHealthMonitoring.Models.HealthMetric", "Metric")
                        .WithMany("Alerts")
                        .HasForeignKey("MetricId")
                        .IsRequired()
                        .HasConstraintName("FK_Alerts_HealthMetrics");

                    b.HasOne("SmartHealthMonitoring.Models.Patient", "Patient")
                        .WithMany("Alerts")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Alerts_Patients");

                    b.Navigation("Metric");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.Appointment", b =>
                {
                    b.HasOne("SmartHealthMonitoring.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointments_Patients");

                    b.HasOne("SmartHealthMonitoring.Models.AppointmentSlot", "Slot")
                        .WithOne("Appointment")
                        .HasForeignKey("SmartHealthMonitoring.Models.Appointment", "SlotId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointments_AppointmentSlots");

                    b.Navigation("Patient");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.AppointmentSlot", b =>
                {
                    b.HasOne("SmartHealthMonitoring.Models.Doctor", "Doctor")
                        .WithMany("AppointmentSlots")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_AppointmentSlots_Doctors");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.AuditLog", b =>
                {
                    b.HasOne("SmartHealthMonitoring.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_AuditLogs_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.Doctor", b =>
                {
                    b.HasOne("SmartHealthMonitoring.Models.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("SmartHealthMonitoring.Models.Doctor", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Doctors_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.GlobalThreshold", b =>
                {
                    b.HasOne("SmartHealthMonitoring.Models.MetricType", "MetricType")
                        .WithMany("GlobalThresholds")
                        .HasForeignKey("MetricTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_GlobalThresholds_MetricTypes");

                    b.Navigation("MetricType");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.HealthMetric", b =>
                {
                    b.HasOne("SmartHealthMonitoring.Models.MetricType", "MetricType")
                        .WithMany("HealthMetrics")
                        .HasForeignKey("MetricTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_HealthMetrics_MetricTypes");

                    b.HasOne("SmartHealthMonitoring.Models.Patient", "Patient")
                        .WithMany("HealthMetrics")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_HealthMetrics_Patients");

                    b.Navigation("MetricType");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.LabResult", b =>
                {
                    b.HasOne("SmartHealthMonitoring.Models.MedicalRecord", "Record")
                        .WithMany("LabResults")
                        .HasForeignKey("RecordId")
                        .IsRequired()
                        .HasConstraintName("FK_LabResults_Records");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.MedicalRecord", b =>
                {
                    b.HasOne("SmartHealthMonitoring.Models.Appointment", "Appointment")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("SmartHealthMonitoring.Models.MedicalRecord", "AppointmentId")
                        .HasConstraintName("FK_MedicalRecords_Appointments");

                    b.HasOne("SmartHealthMonitoring.Models.Doctor", "Doctor")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_MedicalRecords_Doctors");

                    b.HasOne("SmartHealthMonitoring.Models.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_MedicalRecords_Patients");

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.Notification", b =>
                {
                    b.HasOne("SmartHealthMonitoring.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.Patient", b =>
                {
                    b.HasOne("SmartHealthMonitoring.Models.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("SmartHealthMonitoring.Models.Patient", "UserId")
                        .HasConstraintName("FK_Patients_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.User", b =>
                {
                    b.HasOne("SmartHealthMonitoring.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.Appointment", b =>
                {
                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.AppointmentSlot", b =>
                {
                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.Doctor", b =>
                {
                    b.Navigation("AppointmentSlots");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.HealthMetric", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.MedicalRecord", b =>
                {
                    b.Navigation("LabResults");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.MetricType", b =>
                {
                    b.Navigation("GlobalThresholds");

                    b.Navigation("HealthMetrics");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.Patient", b =>
                {
                    b.Navigation("AiInsights");

                    b.Navigation("Alerts");

                    b.Navigation("Appointments");

                    b.Navigation("HealthMetrics");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartHealthMonitoring.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Doctor");

                    b.Navigation("Notifications");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
